add larvecutils and check for main branch

diff --git a/expert/cp-lar-tag b/expert/cp-lar-tag
--- a/expert/cp-lar-tag
+++ b/expert/cp-lar-tag
@@ -14,7 +14,7 @@
 ########################################################################
 
 # Subsidiary packages to be checked.
-declare -a packages=(larana larreco larrecodnn larsim larsimrad larevt lardata larcore lareventdisplay larexamples larg4 larpandora larpandoracontent larwirecell larsoftobj lardataobj lardataalg larcorealg larcoreobj larbatch larutils webevd)
+declare -a packages=(larana larreco larrecodnn larsim larsimrad larevt lardata larcore lareventdisplay larexamples larg4 larpandora larpandoracontent larwirecell larsoftobj larvecutils lardataobj lardataalg larcorealg larcoreobj larbatch larutils webevd)
 
 # Tag message.
 tag_msg='LArSoft suite cross-package tag'
@@ -128,7 +128,12 @@ for package in "${packages[@]}"; do
   cd ${my_working_dir}
   git clone ${repository}/${package}${suffix} || { echo "ERROR: failed to clone ${package}"; exit 1; }
   cd ${my_working_dir}/${package}
-  git checkout master || { echo "ERROR: failed to checkout master for ${package}"; exit 1; }
+  main_branch=master
+  have_main=`git branch -a | grep main | wc -l`
+  if (( ${have_main} != 0 )); then 
+    main_branch=main
+  fi
+  git checkout ${main_branch} || { echo "ERROR: failed to checkout ${main_branch} for ${package}"; exit 1; }
   echo "Apply ${suite_tag} to ${package} ${pkgver}"
   maybe_tag "${suite_tag}" "${pkgver}"
 done
diff --git a/expert/manageLArGithub b/expert/manageLArGithub
--- a/expert/manageLArGithub
+++ b/expert/manageLArGithub
@@ -15,9 +15,9 @@ function usage() {
     echo "   update - modify product_deps release as specified"
 #    echo "   commit - commit changes in product_deps and push the fork"
 #    echo "   pr - initiate a pull request"
-    echo "   tag - tag the master branch"
+    echo "   tag - tag the main branch branch"
     echo "   tagbranch - tag the specified branch"
-    echo "   merge - merge the master branch with develop"
+    echo "   merge - merge the main branch branch with develop"
     echo
     echo "FOR EXPERT USE ONLY"
 
@@ -48,27 +48,32 @@ function maybe_tag() {
     #echo "checking for ${myver} in  ${REP} - found ${have_tag}"
     have_upstream=`git remote -v | grep upstream | wc -l`
     #echo "have_upstream is ${have_upstream}"
+    main_branch=master
+    have_main=`git branch -a | grep main | wc -l`
+    if (( ${have_main} != 0 )); then 
+      main_branch=main
+    fi
     if (( ${have_tag} > 0 )); then
       echo "tag $myver already exists: doing nothing."
     elif (( ${have_upstream} > 0 )); then
       echo "working on a fork in ${REP}"
-      git checkout master
-      git pull upstream master
+      git checkout ${main_branch}
+      git pull upstream ${main_branch}
       code_diff=`git diff release/${tag} | wc -l`
       if (( ${code_diff} > 0 )); then
-	 echo "${REP} master does not match release/${tag} - check and fix"
+	 echo "${REP} ${main_branch} does not match release/${tag} - check and fix"
 	 exit 1
       fi
       git merge -m"${REP} ${version} for larsoft ${larsoft_version}" release/${tag}   || exit 1
       git tag -a -m"${REP} ${version} for larsoft ${larsoft_version}" ${version}  || exit 1
-      git push upstream master ${version} || exit 1
+      git push upstream ${main_branch} ${version} || exit 1
     else
       echo "ready to tag ${REP}"
-      git checkout master  || exit 1
+      git checkout ${main_branch}  || exit 1
       git pull  || exit 1
       git merge -m"${REP} ${version} for larsoft ${larsoft_version}" release/${tag}   || exit 1
       git tag -a -m"${REP} ${version} for larsoft ${larsoft_version}" ${version}  || exit 1
-      git push origin master ${version} || exit 1
+      git push origin ${main_branch} ${version} || exit 1
     fi
 }
 
@@ -271,14 +276,19 @@ then
      echo "begin ${REP}"
      have_upstream=`git remote -v | grep upstream | wc -l`
      echo "have_upstream is ${have_upstream}"
+     main_branch=master
+     have_main=`git branch -a | grep main | wc -l`
+     if (( ${have_main} != 0 )); then 
+       main_branch=main
+     fi
      git checkout develop  || { echo "ERROR: git checkout develop failed"; exit 1; }
      if (( ${have_upstream} > 0 )); then
        git pull upstream develop || { echo "ERROR: git pull develop failed"; exit 1; }
-       git merge -m"larsoft ${tag}" master  || { echo "ERROR: git merge failed"; exit 1; }
+       git merge -m"larsoft ${tag}" ${main_branch}  || { echo "ERROR: git merge failed"; exit 1; }
        git push upstream develop  || { echo "ERROR: git push develop failed"; exit 1; }
      else
        git pull || { echo "ERROR: git pull develop failed"; exit 1; }
-       git merge -m"larsoft ${tag}" master  || { echo "ERROR: git merge failed"; exit 1; }
+       git merge -m"larsoft ${tag}" ${main_branch}  || { echo "ERROR: git merge failed"; exit 1; }
        git push origin develop  || { echo "ERROR: git push develop failed"; exit 1; }
      fi
   done
