hopefully more robust

diff --git a/expert/manageLArGithub b/expert/manageLArGithub
--- a/expert/manageLArGithub
+++ b/expert/manageLArGithub
@@ -2,11 +2,6 @@
 
 # This script presumes that you already have a working mrb directory
 
-# functions: start release branch
-#            update versions 
-#            commit changes and push release branch to fork
-#            make pull request and save content for a test build
-
 # Determine this command name
 thisComFull=$(basename $0)
 fullCom="${thisComFull%.*}"
@@ -17,14 +12,65 @@ function usage() {
     echo "Usage: $fullCom update <major|minor|micro>"
     echo "   start - create release/<tag> branch"
     echo "   update - modify product_deps release as specified"
-    echo "   commit - commit changes in product_deps and push the fork"
-    echo "   pr - initiate a pull request"
+#    echo "   commit - commit changes in product_deps and push the fork"
+#    echo "   pr - initiate a pull request"
     echo "   tag - tag the master branch"
     echo "   merge - merge the master branch with develop"
     echo
     echo "FOR EXPERT USE ONLY"
 
 }
+
+# commit ups/product_deps if necessary
+function commit_ups_product_deps() {
+    set -x
+    have_ups=`git status -s | grep ups/product_deps | wc -l`
+    if (( ${have_ups} != 0 )); then
+      git commit -m"${REP} ${version} for larsoft ${tag}" ups/product_deps  || exit 1
+    fi
+    have_changes=`git status -s | wc -l`
+    if (( ${have_changes} != 0 )); then
+      echo "ERROR: The ${REP} repository contains uncommited changes"
+      echo "       Please commit or otherwise deal with these changes"
+      git status -s
+      exit 1
+    fi
+    set +x
+}
+
+function maybe_tag() {
+    local myver=$1
+    have_tag=`git tag | grep '^'"$myver"'\$' | wc -w`
+    echo "checking for ${myver} in  ${REP} - found ${have_tag}"
+    have_upstream=`git remote -v | grep upstream | wc -l`
+    echo "have_upstream is ${have_upstream}"
+    set -x
+    if (( ${have_tag} > 0 )); then
+      echo "tag $myver already exists: doing nothing."
+    elif (( ${have_upstream} > 0 )); then
+      echo "working on a fork in ${REP}"
+      git checkout master
+      git pull upstream master
+      code_diff=`git diff release/${tag} | wc -l`
+      if (( ${code_diff} > 0 )); then
+	 echo "${REP} master does not match release/${tag} - check and fix"
+	 exit 1
+      fi
+      git merge -m"${REP} ${version} for larsoft ${larsoft_version}" release/${tag}   || exit 1
+      git tag -a -m"${REP} ${version} for larsoft ${larsoft_version}" ${version}  || exit 1
+      git push upstream master ${version} || exit 1
+    else
+      echo "ready to tag ${REP}"
+      git checkout master  || exit 1
+      git pull  || exit 1
+      git merge release/${tag}   || exit 1
+      git tag -a -m"${REP} ${version} for larsoft ${larsoft_version}" ${version}  || exit 1
+      git push origin master ${version} || exit 1
+    fi
+    set +x
+}
+
+################################################################################
 
 # Determine command options (just -h for help)
 while getopts ":h" OPTION
@@ -49,8 +95,8 @@ fi
 case $flow in
     start ) ;;
     update ) ;;
-    commit ) ;;
-    pr ) ;;
+#    commit ) ;;
+#    pr ) ;;
     tag ) ;;
     merge ) ;;
     *   ) echo "ERROR: Unknown option $flow" ; usage ; exit 1 ;;
@@ -131,6 +177,46 @@ then
   done
 fi
 
+if [ "${flow}" = "tag" ]
+then
+  larsoft_version=`grep larsoft ${MRB_SOURCE}/larsoft/ups/product_deps | grep parent | tr -s '[:space:]' | cut -f3 -d " "`
+  echo "found larsoft_version ${larsoft_version}"
+  for REP in $pkglist
+  do
+     cd ${MRB_SOURCE}/${REP}
+     # make sure we are on the expected branch
+     git checkout release/${tag}  || exit 1
+     version=`grep ${REP} ups/product_deps | grep parent | sed -e 's/[[:space:]]/ /g' | cut -f3 -d " "`
+     echo "begin ${REP} ${version}"
+     commit_ups_product_deps
+     maybe_tag "${version}"
+  done
+fi
+
+if [ "${flow}" = "merge" ]
+then
+  for REP in $pkglist
+  do
+     cd ${MRB_SOURCE}/${REP}
+     echo "begin ${REP}"
+     have_upstream=`git remote -v | grep upstream | wc -l`
+     echo "have_upstream is ${have_upstream}"
+     git checkout develop  || { echo "ERROR: git checkout develop failed"; exit 1; }
+     if (( ${have_upstream} > 0 )); then
+       git pull upstream develop || { echo "ERROR: git pull develop failed"; exit 1; }
+       git merge -m"larsoft ${tag}" master  || { echo "ERROR: git merge failed"; exit 1; }
+       git push upstream develop  || { echo "ERROR: git push develop failed"; exit 1; }
+     else
+       git pull || { echo "ERROR: git pull develop failed"; exit 1; }
+       git merge master  || { echo "ERROR: git merge failed"; exit 1; }
+       git push origin develop  || { echo "ERROR: git push develop failed"; exit 1; }
+     fi
+  done
+fi
+
+exit 0
+
+# The commit option is disabled
 if [ "${flow}" = "commit" ]
 then
   branch=release/${tag}
@@ -162,6 +248,7 @@ then
   done
 fi
 
+# The pr option is disabled
 if [ "${flow}" = "pr" ]
 then
   cfg_file=${MRB_SOURCE}/larsoft-${tag}-prs
@@ -191,37 +278,3 @@ then
   echo "buildPR -q <quals> <build dir> ${pkgPRs[*]}" >> ${cfg_file}
   echo "" >> ${cfg_file}
 fi
-
-if [ "${flow}" = "tag" ]
-then
-  for REP in $pkglist
-  do
-     cd ${MRB_SOURCE}/${REP}
-     echo "begin ${REP}"
-     git checkout master
-     git pull upstream master
-     code_diff=`git diff release/${tag} | wc -l`
-     if (( ${code_diff} > 0 )); then
-	echo "${REP} master does not match release/${tag} - check and fix"
-	exit 1
-     fi
-     version=`grep ${REP} ups/product_deps | grep parent | sed -e 's/[[:space:]]/ /g' | cut -f3 -d " "`
-     git tag -a -m"${REP} ${version} for larsoft ${tag}" ${version}  || exit 1
-     git push upstream master ${version} || exit 1
-  done
-fi
-
-if [ "${flow}" = "merge" ]
-then
-  for REP in $pkglist
-  do
-     cd ${MRB_SOURCE}/${REP}
-     echo "begin ${REP}"
-     git checkout develop  || { echo "ERROR: git checkout develop failed"; exit 1; }
-     git pull upstream develop || { echo "ERROR: git pull develop failed"; exit 1; }
-     git merge -m"larsoft ${tag}" master  || { echo "ERROR: git merge failed"; exit 1; }
-     git push upstream develop  || { echo "ERROR: git push develop failed"; exit 1; }
-  done
-fi
-
-exit 0
