add e20 build directories and disable lariat

diff --git a/expert/startLArSoftRel b/expert/startLArSoftRel
--- a/expert/startLArSoftRel
+++ b/expert/startLArSoftRel
@@ -32,10 +32,13 @@ create_working_directory() {
       exit 1
   fi
   mkdir -p ${working_dir}/${tag} || { echo "ERROR: failed to create ${working_dir}/${tag}"; exit 1; }
+  mkdir -p ${working_dir}/${tag}/e20p  ${working_dir}/${tag}/e20d || { echo "ERROR: failed to create ${working_dir}/${tag}/e20p"; exit 1; }
   mkdir -p ${working_dir}/${tag}/e19p  ${working_dir}/${tag}/e19d || { echo "ERROR: failed to create ${working_dir}/${tag}/e19p"; exit 1; }
   mkdir -p ${working_dir}/${tag}/c7p  ${working_dir}/${tag}/c7d || { echo "ERROR: failed to create ${working_dir}/${tag}/c7p"; exit 1; }
   cd ${working_dir}/${tag}
   echo "run mrb newDev"
+  mrb newDev -f -v ${tag} -q e20:prof -T e20p || exit 1
+  mrb newDev -f -v ${tag} -q e20:debug -T e20d || exit 1
   mrb newDev -f -v ${tag} -q e19:prof -T e19p || exit 1
   mrb newDev -f -v ${tag} -q e19:debug -T e19d || exit 1
   mrb newDev -f -v ${tag} -q c7:prof -T c7p || exit 1
@@ -62,19 +65,21 @@ create_working_directory() {
     mrb g dunetpc
     echo "checkout duneutil"
     mrb g duneutil
-    echo "checkout lariatsoft"
-    mrb g lariatsoft
-    mrb g lariatfragments
-    mrb g lariatutil
-    echo "checkout sbndcode"
-    mrb g sbndcode
-    mrb g sbndutil
+    # LArIAT is hopelessly out of date
+    #echo "checkout lariatsoft"
+    #mrb g lariatsoft
+    #mrb g lariatfragments
+    #mrb g lariatutil
+    # should replace with sbn, icarus, and sbnd
+    #echo "checkout sbndcode"
+    #mrb g sbndcode
+    #mrb g sbndutil
+    ##echo "checkout icaruscode"
+    ##mrb g icaruscode
     echo "checkout uboonecode"
     mrb  g uboone_suite
     echo "checkout argoneutcode"
     mrb g argoneutcode
-    ##echo "checkout icaruscode"
-    ##mrb g icaruscode
   elif [[ ${extra_options} == "argoneut" ]]; then
     echo "checkout argoneutcode"
     mrb g argoneutcode
