use updateVersion and drop c2 and e17

diff --git a/expert/tagLAr b/expert/tagLAr
--- a/expert/tagLAr
+++ b/expert/tagLAr
@@ -10,7 +10,7 @@
 # mrb g argoneutcode
 # mrb g lariatsoft
 # tagLar start <tag>
-# tagLar update <tag>
+# tagLar update <major|minor|micro>
 # mrb uv other products if necessary
 # verify build, test, and install 
 # tagLar tag <tag>
@@ -29,11 +29,12 @@ fullCom="${thisComFull%.*}"
 
 # Usage function
 function usage() {
-    echo "Usage: $fullCom <start|update|tag|merge> <tag>"
+    echo "Usage: $fullCom <start|tag|merge> <tag>"
     echo "Usage: $fullCom feature <new tag>"
     echo "Usage: $fullCom patch <new tag> <existing tag>"
     echo "Usage: $fullCom branch <new branch> <existing tag>"
     echo "Usage: $fullCom tagbranch <existing branch> <new tag>"
+    echo "Usage: $fullCom update <major|minor|micro>"
     echo "Usage: $fullCom mkdir <new tag> <working_dir>"
     echo "   mkdir  - mkdir <working_dir>/<tag>, run newDev, then checkout larsoft_suite and experiment code"
     echo "   start - create release/<tag> branch"
@@ -41,7 +42,7 @@ function usage() {
     echo "   patch - create release/<tag> branch based on existing tag"
     echo "   branch - create <branch> branch based on existing tag"
     echo "   use - use existing <branch> branch"
-    echo "   update - modify product_deps to use <tag>"
+    echo "   update - modify product_deps release as specified"
     echo "   tag - merge changes with master and tag"
     echo "   tagbranch - tag the designated branch"
     echo "   force - merge changes with master and force update of existing tag"
@@ -69,20 +70,14 @@ create_working_directory() {
   mkdir -p ${working_dir}/${tag} || { echo "ERROR: failed to create ${working_dir}/${tag}"; exit 1; }
   mkdir -p ${working_dir}/${tag}/e19p  ${working_dir}/${tag}/e19d || { echo "ERROR: failed to create ${working_dir}/${tag}/e19p"; exit 1; }
   mkdir -p ${working_dir}/${tag}/c7p  ${working_dir}/${tag}/c7d || { echo "ERROR: failed to create ${working_dir}/${tag}/c7p"; exit 1; }
-  mkdir -p ${working_dir}/${tag}/e17p  ${working_dir}/${tag}/e17d || { echo "ERROR: failed to create ${working_dir}/${tag}/e17p"; exit 1; }
-  mkdir -p ${working_dir}/${tag}/c2p  ${working_dir}/${tag}/c2d || { echo "ERROR: failed to create ${working_dir}/${tag}/c2p"; exit 1; }
   cd ${working_dir}/${tag}
   echo "run mrb newDev"
   mrb newDev -f -v ${tag} -q e19:prof -T e19p || exit 1
   mrb newDev -f -v ${tag} -q e19:debug -T e19d || exit 1
   mrb newDev -f -v ${tag} -q c7:prof -T c7p || exit 1
   mrb newDev -f -v ${tag} -q c7:debug -T c7d || exit 1
-  mrb newDev -f -v ${tag} -q e17:prof -T e17p || exit 1
-  mrb newDev -f -v ${tag} -q e17:debug -T e17d || exit 1
-  mrb newDev -f -v ${tag} -q c2:prof -T c2p || exit 1
-  mrb newDev -f -v ${tag} -q c2:debug -T c2d || exit 1
   echo "source localProductsXXX/setup"
-  source e17p/localProducts*/setup
+  source e19p/localProducts*/setup
   cd $MRB_SOURCE
   echo "checkout larsoft_suite"
   mrb g larsoft_suite
@@ -288,10 +283,16 @@ fi
 
 if [ "${flow}" = "update" ]
 then
-  for REP in $pkglist
-  do
-     mrb uv ${REP} ${tag}
-  done
+  case  ${tag} in
+    major ) ;;
+    minor ) ;;
+    micro ) ::
+    * ) echo "ERROR: unrecognized option ${tag}
+        echo "       Please specify major, minor, or micro."
+	exit 1; ;;
+  esac
+  echo "calling updateVersion ${tag}"
+  updateVersion ${tag}
 fi
 
 if [ "${flow}" = "tag" ]
